-ifndef(_MIDI_INTEGRA_7_HRL_).
-define(_MIDI_INTEGRA_7_HRL_, true).

%% INTEGRA-7 definitions
-define(MIDI_CTRL_INTEGRA_7_LEFT_RIGHT,  12).  %% INTEGRA-7 L-R
-define(MIDI_CTRL_INTEGRA_7_FRONT_BACK,  13).  %% INTEGRA-7 F-B
-define(MIDI_CTRL_INTEGRA_7_AMBIENCE,    14).  %% INTEGRA-7 Ambience
-define(MIDI_CTRL_INTEGRA_7_LEFT_RIGHT_FINE,  28).  %% INTEGRA-7 L-R
-define(MIDI_CTRL_INTEGRA_7_FRONT_BACK_FINE,  29).  %% INTEGRA-7 F-B
-define(MIDI_CTRL_INTEGRA_7_AMBIENCE_FINE,    30).  %% INTEGRA-7 Ambience

-endif.
