-ifndef(_MIDI_PROPHET_6_HRL_).
-define(_MIDI_PROPHET_6_HRL_, true).

-define(OSC_1_FREQ,0).
-define(OSC_1_SYNC,1).
-define(OSC_1_LEVEL,2).
-define(OSC_1_SHAPE,3).
-define(OSC_1_PULSE_WIDTH,4).
-define(OSC_2_FREQ, 5).
-define(OSC_2_FREQ_FINEM,6).
-define(OSC_2_LEVEL,7).
-define(OSC_2_SHAPE,8).
-define(OSC_2_PULSE_WIDTH,9).
-define(OSC_2_LOW_FREQ, 10).
-define(OSC_2_KEY_ON_OFF,11).
-define(OSC_1_SUB_LEVEL,27).
-define(GLIDE_MODE,28).
-define(GLIDE_ON_OFF,29).
-define(GLIDE_RATE,30).
-define(PBEND_RANGE,31).
-define(NOISE_LEVEL,32).
-define(SLOP,33).
-define(LOW_PASS_FREQ,45).
-define(VCA_ENV_DECAY,68).
-define(VCA_ENV_SUSTAIN,69).
-define(VCA_ENV_RELEASE,70).
-define(VCA_ENV_VEL_ON_OFF,71).
-define(LOW_PASS_ENV_AMT,77).
-define(FILTER_ENV_ATTACK,78).
-define(FILTER_ENV_DECAY,79).
-define(FILTER_ENV_SUSTAIN,80).
-define(FILTER_ENV_RELEASE,81).
-define(HIGH_PASS_ENV_AMT,82).
-define(LFO_FREQ,88).
-define(LFO_INITIAL_AMT,89).
-define(LFO_SHAPE,90).
-define(LFO_SYNC,91).
-define(LFO_FREQ_1_DEST_ON_OFF,93).
-define(LFO_FREQ_2_DEST_ON_OFF,94).
-define(LFO_PW_1_2_DEST_ON_OFF,95).
-define(LFO_AMP_DEST_ON_OFF,96).


-endif.

